[theme]
theme = "native"

[icons]
icons = "none"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
missing_format = ""

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1
format = "$utilization $frequency"

[[block]]
block = "memory"
format = "$icon $mem_free/$mem_avail($mem_total_used_percents)"
format_alt = "$icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2))"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'dow %u, week %U, %Y-%m-%d(%a) %H:%M:%S')"
