{ config, options, lib, pkgs, ... }:
{
  imports = [
    ./etc.nix
    ./dunst.nix
    ./bash.nix
    ./tmux.nix
    ./git.nix
    ./email.nix
    ./sops.nix
    ./pass.nix
    ./fzf.nix
    ./navi.nix
    ./audio.nix
    ./sway.nix
    ./alacritty.nix
    ./pueue.nix
    ./nushell.nix
    ./yazi.nix
    ./xplr.nix
    ./zathura.nix
    ./rofi.nix
    ./broot.nix
    ./zk.nix
    ./less.nix
    ./taskwarrior.nix
    ./procs.nix
    ./mpd.nix
  ];
}
