# https://nixos.org/manual/nix/unstable/command-ref/conf-file.html
extra-experimental-features = nix-command flakes
substituters = https://attic.p.intranet.dgeng.eu/ci https://cache.nixos.org
trusted-public-keys = ci:+ViOOuXEpfKsAmNNi5i1qHJ0R7WlIqqJHZ6tr1E7P9Y= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
netrc-file = /home/intranet.dgeng.eu/dgeng/.config/nix/netrc
