#!/usr/bin/env bash
alias pulse_list_input="pacmd list-sources | grep -e device.string -e 'name:'"
alias pulse_list_output="pacmd list-sinks | grep -e 'name:' -e 'index'"
rec() { arecord -f dat $HOME/me/recordings/audio/rec$(date +%Y%m%d%M%S).wav}; }

################################################################################
# media
# ------------------------------------------------------------------------------
alias mpct="mpc toggle"
alias mpcp="mpc play"
alias mpcs="mpc stop"
alias mpca="mpc add"
alias mpcls="mpc ls"
alias mpcn="mpc next"
alias mpcpr="mpc prev"
alias mpcv="mpc vol"
alias mpcu="mpc update"
