#!/usr/bin/env bash
declarealias vimwiki
declarealias vimwiki_select
#alias journal_note="vim -c VimwikiMakeDiaryNote"
#alias journal_select="vim -c VimwikiUISelect -c VimwikiDiaryIndex -c VimwikiDiaryGenerateLinks"
#alias journal="vim -c VimwikiDiaryIndex -c VimwikiDiaryGenerateLinks"
declarealias journal

################################################################################
# io 
# ------------------------------------------------------------------------------
alias echoerr=">&2 echo"

################################################################################
# etc
# ------------------------------------------------------------------------------
alias transde="trans en:de"
alias transen="trans de:en"
alias transru="trans de:ru"
alias p=$PAGER

################################################################################
# script alias
# ------------------------------------------------------------------------------
declarealias tmuxn
tmuxncd() { local path=$1;shift; tmux_new_session.sh -p "$path" "$@"; }
declarealias r
declarealias rq
