#!/usr/bin/env bash
################################################################################
# system
# ------------------------------------------------------------------------------
alias sudok="sudo --reset-timestamp"
alias sudokill="sudo --remove-timestamp"
alias napnow="{ command -v timew 2>&1 | logger -t bashrc -p user.info && timew stop; command -v i3lock 2>&1 | logger -t bashrc -p user.info && i3lock -c 000000; systemctl suspend; }"

alias shutdown="systemctl poweroff"
alias restart="systemctl reboot"

alias sctl="systemctl"
alias sctlls="sctl list-unit-files"
alias sctlreload="sctl daemon-reload"
alias sctlstart="sctl start"
alias sctlstop="sctl stop"

alias sctlu="sctl --user"
alias sctluls="sctlu list-unit-files"

alias jctl=journalctl
alias jctlf="journalctl -f"
alias jctle="journalctl -e"

alias pushdbashd="pushd $PATH_BASH_CONFIG"
alias root="sudo -i"

# clipboard
alias systemclipboard="xclip -selection c"
alias clip=systemclipboard
alias clipclear="printf '' | xclip -i"
alias clippaste="systemclipboard -o"

alias h="history"
alias htail="history 10"
alias j="jobs -l"

# getent
alias getu="getent passwd"
alias getg="getent group"
alias geta="getent aliases"
alias geth="getent ahosts"
alias geth4="getent ahostsv4"
alias geth6="getent ahostsv6"
alias getp="getent protocols"
alias gets="getent services"

alias freeh="free -h"

################################################################################
# editing
# ------------------------------------------------------------------------------
alias f=f.sh
alias c=bat
alias l=less
alias vim=nvim
alias v=vim
alias vi="vim"
alias vimr="vim -R"
alias view=vimr
alias edit="vim"
alias nvimdiff="nvim -d"
alias info="info --vi-keys"
alias pager="$PAGER"
alias rgh="rg --hidden"
alias rgs="rg --case-sensitive"
alias rgl="rg --files-with-matches"
alias rgL="rg --follow"
alias rgv="rg --invert-match"
alias rgjson="rg --json"
alias rgbuffer="rg --line-buffered" # default already
alias rgnobuffer="rg --no-line-buffered"
alias rgn="rg --line-number"
alias rgU="rg --multiline --multiline-dotall"        # enable multiline and dot . match to newline
alias rgnoignore="rg --no-ignore --no-ignore-global" # ignore .gitignore, excludes etc
alias rgo="rg --only-matching"
alias rgw="rg --word-regexp"
alias frg="rg --fixed-strings"
alias rgtest="rg --files" # no search show only files which will be searched
