#!/usr/bin/env bash
declarealias vimwiki "::\ vimwiki"
declarealias vimwiki_select "::\ vimwiki_select"
#alias journal_note="vim -c VimwikiMakeDiaryNote"
#alias journal_select="vim -c VimwikiUISelect -c VimwikiDiaryIndex -c VimwikiDiaryGenerateLinks"
#alias journal="vim -c VimwikiDiaryIndex -c VimwikiDiaryGenerateLinks"
declarealias journal "default ::\ journal"
declarealias mindmap "default ::\ mindmap"
declarealias browser "default ::\ browser"
declarealias webcamrecorder "default gui\ ::\ webcamrecorder"

################################################################################
# apps
# ------------------------------------------------------------------------------
alias pq=pueue
alias pqs="pueue status"
alias pqa="pueue add"

################################################################################
# io 
# ------------------------------------------------------------------------------
alias echoerr=">&2 echo"

################################################################################
# etc
# ------------------------------------------------------------------------------
alias transde="trans en:de"
alias transen="trans de:en"
alias transru="trans de:ru"

################################################################################
# script alias
# ------------------------------------------------------------------------------
alias tmuxn="tmux_new_session.sh"
alias tmuxnd="tmux_new_session.sh -d"
alias r="run.sh"
alias rq="run.sh -q -n"
alias re="run.sh -e"
alias tmuxr="tmux_run_session.sh"
