#!/usr/bin/env bash
################################################################################
# media
# ------------------------------------------------------------------------------
alias mpct="mpc toggle"
alias mpcp="mpc play"
alias mpcs="mpc stop"
alias mpca="mpc add"
alias mpcls="mpc ls"
alias mpcn="mpc next"
alias mpcpr="mpc prev"
alias mpcv="mpc vol"
alias mpcu="mpc update"
