#!/usr/bin/env bash
alias gpg="gpg -i"
alias gpge="gpg --armor --batch --encrypt -r"
alias gpgd="gpg --decrypt -r"
alias gpgv="gpg --verify -r"
alias gpgs="gpg --sign -r"
alias gpg_gen="gpg --generate-key"
alias gpgls="gpg -K; gpg -k"
alias gpgll="gpg --keyid-format 0xlong -K; gpg --keyid-format 0xlong -k"
alias gpglsa="gpg -K --list-options show-unusable-subkeys; gpg -k --list-options show-unusable-subkeys"
alias gpglsf="gpg -K --with-fingerprint; gpg -k --with-subkey-fingerprint"
alias gpglsaf="gpg -K --list-options show-unusable-subkeys --with-fingerprint; gpg -k --list-options show-unusable-subkeys --with-subkey-fingerprint"
alias gpgi="gpg --import"
alias gpg_exp="gpg --export"
alias gpg_expsk="gpg --export-secret-keys"
alias gpg_exp_subk="gpg --export-secret-subkeys"
alias gpg_exppaper="gpg --export-secret-keys --armor"
alias gpg_ssh="gpg --export-ssh-key"
alias gpg_finger="gpg --fingerprint --fingerprint"
alias gpglsgrip="gpg -K --with-keygrip; gpg -k --with-keygrip"
alias gpgdela="gpg --delete-secret-and-public-key"
alias gpgdel="gpg --delete-keys"
alias gpgdelsec="gpg --delete-secret-keys"

gpg_restart() {
  local sockets=(
  gpg-agent.socket
  gpg-agent-browser.socket
  gpg-agent-ssh.socket
  gpg-agent-extra.socket
  )
  systemctl --user stop "${sockets[@]}"
  systemctl --user stop gpg-agent
  systemctl --user start "${sockets[@]}"
  systemctl --user start gpg-agent
}
