#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [[ -x /usr/bin/dircolors ]]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

if hash bat; then
  alias cat=bat
fi
alias c="bat -p"
alias ls=eza
alias ll="eza -l"
alias lla="eza -la"
alias la="eza -a"
alias t="tree -C | $PAGER"

alias rm="rm -i --preserve-root"
alias rmi="rm -I --preserve-root"
alias mv="mv -i"
alias cp="cp -i"
alias ln="ln -i"

alias chown="chown --preserve-root"
alias chmod="chmod --preserve-root"
alias chgrp="chgrp --preserve-root"

alias fdd="fd --type d"
alias fdf="fd --type f"
alias findd="find . -type d"
alias findf="find . -type f"
alias finddeadlink="find . -xtype l"

# navigation
alias pu="pushd"
alias po="popd"
alias pua="pushd_all"

alias ..="builtin cd .."
alias ...="builtin cd ../.."

declarealias p "fuzzy search and preview files with bat"
