#!/usr/bin/env bash
alias epoch="date --date @"
alias now="date +%T"
alias today="date +%F"
alias datefilename="date +%Y%m%dT%H%M%S"
alias nowa=datefilename
alias dateiso="date --iso-8602=ns"
alias daterfc3339nano="date +%FT%T.%N%:z"
alias dateT=dateiso
