#!/usr/bin/env bash
set -a
################################################################################
# Python
# ------------------------------------------------------------------------------
PYTHONSTARTUP="${PATH_USER_LIB}startup.py"
PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
################################################################################
# JAVA
# openjdk
# ------------------------------------------------------------------------------
#JAVA_HOME="/usr/local/java/jdk1.8.0_40"
# oracle
JAVA_HOME="/usr/lib/jvm/java-17-jdk"
JUNIT_HOME="/usr/local/java/JUnit/"
CLASSPATH="$CLASSPATH:$JUNIT_HOME/junit4.10.jar"
CLASSPATH="$CLASSPATH:$JAVA_HOME/lib/"
ANDROID_HOME="/usr/local/android/android-sdk-linux/tools/"
ANDROID_HOME="$ANDROID_HOME:/opt/android-sdk"
COOKIECUTTER_CONFIG="$HOME/.cookiecutterrc"

################################################################################
# Rust
# ------------------------------------------------------------------------------
CARGO_HOME="/data/tmp/$USER/cargo"
RUSTUP_HOME="/data/tmp/$USER/rustup"

# nix
NIX_REMOTE=daemon

set +a

################################################################################
# Ruby
# ------------------------------------------------------------------------------
if command -v ruby 2>&1 | logger -t bashrc -p user.info; then
	export RUBYPATH="$(ruby -e 'puts Gem.user_dir')/bin" # is this even required?
fi
