#!/usr/bin/env bash
set -a 
################################################################################
# etc
# ------------------------------------------------------------------------------
LESS="-RSWFX $LESS"
LESSCHARSET=utf-8
PAGER="less"
#if hash "vimpager"; then
#  PAGER="vimpager"
#  SYSTEMD_PAGER="$PAGER"
#else
#  SYSTEMD_PAGER="$PAGER"
#fi
SYSTEMD_PAGER="$PAGER"
EDITOR="vim"
SYSTEMD_EDITOR="$EDITOR"
VISUAL="$EDITOR"
SUDO_EDITOR="$EDITOR"
BAT_THEME="ansi"

LIBVIRT_DEFAULT_URI="qemu:///system"

# WINE
# ------------------------------------------------------------------------------
WINEPREFIX="$HOME/.config/wine/"
WINEARCH="win64"

# apps
# ------------------------------------------------------------------------------
RANGER_LOAD_DEFAULT_RC=TRUE
SOURCE_LANG="en"
TARGET_LANG="de"
HOME_LANG="de"
NQDIR=$TMP

################################################################################
# fzf
# ------------------------------------------------------------------------------
set +a
if hash fzf 2>&1 >/dev/null | logger -s -t bashrc -p user.info; then
  if hash fd 2>&1 >/dev/null | logger -s -t bashrc -p user.info; then
    FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude ".git"'
  elif hash rg 2>&1 >/dev/null | logger -s -t bashrc -p user.info; then
    FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
  fi
  FZF_DEFAULT_OPTS='--bind alt-p:accept'
  FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:#cccccc,bg:#000000,hl:#de382b --color=fg+:#ffffff,bg+:#000000,hl+:#ff0000 --color=info:#9a9a9a,prompt:#007acc,pointer:#ff0000 --color=marker:#39b54a,spinner:#9a9a9a,header:#9a9a9a'
  FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
  FZF_ALT_C_COMMAND="fd --type d --min-depth 1 --hidden --follow --no-ignore-vcs --exclude '.git'"
  FZF_COMPLETION_OPTS="--preview 'if test -f {}; then bat --color=always --style=numbers --line-range=:500 {}; else tree -C {} | head -200;fi'"
  FZF_CTRL_T_OPTS="--preview 'if test -f {}; then bat --color=always --style=numbers --line-range=:500 {}; else tree -C {} | head -200;fi'"
  FZF_CTRL_T_COMMAND="fd --follow --min-depth 1"
  FZF_TMUX_HEIGHT="100%"
fi
